### ISSUE TITLE
COC page

### ISSUE THREAD

**Issue by ricco386** [pyconsk/2018.pycon.sk#2]
Add coc page. You can copy text from https://2017.pycon.sk/code-of-conduct/

**Comment by ZoltanOnody** [comment]
done https://github.com/pyconsk/2018.pycon.sk/commit/1059a5d83edf7e5cffd1eb79bb95cd216d00bf70

**Comment by ZoltanOnody** [comment]
done https://github.com/pyconsk/2018.pycon.sk/commit/5c4f701e954ea650a8bd874d8beebaf5c671bd43
